---
micronaut:
  application:
    name: kuvasz
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SIGNATURE_SECRET}
        generator:
          refresh-token:
            enabled: false
    intercept-url-map:
      - pattern: /health
        access: isAnonymous()
      - pattern: /swagger-ui/**
        access: isAnonymous()
      - pattern: /swagger/**
        access: isAnonymous()
      - pattern: /**
        access:
          - ROLE_ADMIN
    basic-auth:
      enabled: true
  router:
    versioning:
      enabled: true
      default-version: 1
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  http:
    client:
      follow-redirects: false
---
datasources:
  default:
    url: ${DATABASE_JDBC_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: 'org.postgresql.Driver'
    schema: 'kuvasz'
---
flyway:
  datasources:
    default:
      enabled: true
---
jackson:
  bean-introspection-module: true
  serialization-inclusion: always
  date-format: "yyyy-MM-dd'T'HH:mm:ssZ"
---
jooq:
  datasources:
    default:
      sql-dialect: POSTGRES
---
app-config:
  user: ${ADMIN_USER}
  password: ${ADMIN_PASSWORD}
