---
micronaut:
  application:
    name: kuvasz
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SIGNATURE_SECRET}
        generator:
          refresh-token:
            enabled: false
    intercept-url-map:
      - pattern: /health
        access: isAnonymous()
      - pattern: /info
        access: isAnonymous()
      - pattern: /swagger-ui/**
        access: isAnonymous()
      - pattern: /swagger/**
        access: isAnonymous()
      - pattern: /**
        access:
          - ROLE_ADMIN
  router:
    versioning:
      enabled: true
      default-version: 1
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  http:
    client:
      follow-redirects: false
  netty:
    event-loops:
      uptime-check:
        num-threads: 20
        prefer-native-transport: true
        executor: 'io'
endpoints:
  health:
    enabled: true
    sensitive: true
  info:
    enabled: true
    sensitive: false
---
datasources:
  default:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: 'org.postgresql.Driver'
    schema: 'kuvasz'
    maxLifetime: 100000
    maximumPoolSize: 10
---
flyway:
  datasources:
    default:
      enabled: true
---
jackson:
  bean-introspection-module: true
  serialization-inclusion: always
  serialization:
    - WRITE_DATES_AS_TIMESTAMPS: false
---
jooq:
  datasources:
    default:
      sql-dialect: POSTGRES
---
app-config:
  data-retention-days: ${DATA_RETENTION_DAYS:`30`}
---
http-communication-log:
  enabled: ${ENABLE_HTTP_COMMUNICATION_LOG:`false`}
---
handler-config:
  log-event-handler:
    enabled: ${ENABLE_LOG_EVENT_HANDLER:`true`}
  smtp-event-handler:
    enabled: ${ENABLE_SMTP_EVENT_HANDLER:`false`}
    from: ${SMTP_FROM_ADDRESS}
    to: ${SMTP_TO_ADDRESS}
  slack-event-handler:
    enabled: ${ENABLE_SLACK_EVENT_HANDLER:`false`}
    webhook-url: ${SLACK_WEBHOOK_URL}
  telegram-event-handler:
    enabled: ${ENABLE_TELEGRAM_EVENT_HANDLER:`false`}
    token: ${TELEGRAM_API_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}
  pagerduty-event-handler:
    enabled: ${ENABLE_PAGERDUTY_EVENT_HANDLER:`false`}
---
admin-auth:
  username: ${ADMIN_USER}
  password: ${ADMIN_PASSWORD}
---
smtp-config:
  host: ${SMTP_HOST}
  port: ${SMTP_PORT}
  username: ${SMTP_USERNAME:``}
  password: ${SMTP_PASSWORD:``}
  transport-strategy: ${SMTP_TRANSPORT_STRATEGY:`SMTP_TLS`}
